### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by cmandlbaur** [haxiomic/haxe-script-utils#1]
Just an FYI on Windows support status.

Command prompt - Not functional
Powershell - Not functional
cmder/ConEmu - Pretty good
git bash - Throws an error whilst running through the tests, but has basic colour support.

![virtualbox_testo_05_09_2017_23_38_43](https://user-images.githubusercontent.com/1900059/30084664-a396a4da-9293-11e7-85fd-8a94a790d43a.png)
![virtualbox_testo_05_09_2017_23_39_03](https://user-images.githubusercontent.com/1900059/30084665-a3f01ef2-9293-11e7-8c9f-9dbb3a6e153e.png)
![virtualbox_testo_05_09_2017_23_39_25](https://user-images.githubusercontent.com/1900059/30084667-a3f905b2-9293-11e7-9b91-88d0a1424394.png)
![virtualbox_testo_05_09_2017_23_39_42](https://user-images.githubusercontent.com/1900059/30084666-a3f2a942-9293-11e7-9917-49da915bd154.png)

Happy to test

**Comment by haxiomic** [comment]
Hey Chris,

Thanks for taking the time to test! These are really interesting results

**Command Prompt** - wow that's a mess! Historically it has had no color support out of the box, more recently in Windows 10 it can now support the same color codes that mac and linux terminals use but it [needs to be enabled](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences), which I might be able to do within the library. Nevertheless, when formatting isn't supported in the console it shouldn't print all the junk!

**Powershell** - It looks like there's a [trick to this](https://stackoverflow.com/a/36519870), so we should be able to support this

**Cmder** - This one is nearly there, looks like utf-8 isn't enabled out of the box but there's a [command to enable it](https://github.com/cmderdev/cmder/issues/119). It also looks to be limited to 16 colors rather than 256, I think there's an [option to enable 256](https://conemu.github.io/en/Xterm256Colors.html#xterm_256_color_mode_requirements) in the settings but probably nothing that can be done by the program itself

**Git Bash** - Pretty close, however the "Error: something went wrong" printed at the bottom of the git bash test is curious because it should have been printed above "Success!"

I'm going to get a Windows VM going this week and see what can be done

Here's how I expect it to look (at least with my terminal color scheme)
![expected](https://user-images.githubusercontent.com/3742992/30087776-79b100fa-929a-11e7-8087-5525e9863fee.png)

**Comment by haxiomic** [comment]
Hey @cmandlbaur, try again with the latest changes - colored output (with correct utf-8 charset) should work in Command Prompt and others for the C++ and Neko targets. The caveat is that it requires a fairly up-to-date version of Windows 10

![colorful cmd](https://user-images.githubusercontent.com/3742992/30245642-963dbf56-95d8-11e7-8e9e-be005bd9c6f6.PNG)

**Comment by cmandlbaur** [comment]
Will try when I get a gap, just trying to wrap some things up and then will be traveling to the summit.
